[workspace]
resolver = "2"
members = [
    "crates/flutter_bridge",
]

exclude = [
    "flutter",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
rust-version = "1.79.0"
authors = ["Haled Odat <haledodat@gmail.com>"]
repository = "https://github.com/HalidOdat/stride"
license = "Apache-2.0"
description = "An extensible task menagment application that uses git as it's data store."

[workspace.dependencies]
# Repository Crates
stride_flutter_bridge = { version = "~0.1.0", path = "crates/flutter_bridge" }

# Shared Dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
uuid = { version = "1.7", features = ["v7", "serde"] }
chrono = { version = "0.4", features = ["serde"]}
anyhow = "1.0"
thiserror = "1.0"
lazy_static = "1.4"
git2 = { version = "0.19", default-features = false, features = ["ssh", "ssh_key_from_memory", "vendored-libgit2", "vendored-openssl"] }
base64 = "0.22"
openssl = { version = "0.10", features = ["vendored"] }
pem = "3.0"
log = "0.4"
env_logger = "0.11"

[profile.release]
# Strips debug information and symbols from the binary
strip = "symbols"
opt-level = "s"
lto = "thin"
codegen-units = 1

[profile.release-debug]
inherits = "release"
debug = true
strip = "none"

[workspace.lints.rust]
# rustc lint groups https://doc.rust-lang.org/rustc/lints/groups.html
warnings = "warn"
future_incompatible = "warn"
let_underscore = "warn"
nonstandard_style = "warn"
rust_2018_compatibility = "warn"
rust_2018_idioms = "warn"
rust_2021_compatibility = "warn"
unused = "warn"

# rustc allowed-by-default lints https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html
# missing_docs = "warn"
macro_use_extern_crate = "warn"
meta_variable_misuse = "warn"
missing_abi = "warn"
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
non_ascii_idents = "warn"
noop_method_call = "warn"
single_use_lifetimes = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unreachable_pub = "warn"
unsafe_op_in_unsafe_fn = "warn"
unused_crate_dependencies = "warn"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"
variant_size_differences = "warn"

[workspace.lints.rustdoc]
# rustdoc lints https://doc.rust-lang.org/rustdoc/lints.html
broken_intra_doc_links = "warn"
private_intra_doc_links = "warn"
missing_crate_level_docs = "warn"
private_doc_tests = "warn"
invalid_codeblock_attributes = "warn"
invalid_rust_codeblocks = "warn"
bare_urls = "warn"

[workspace.lints.clippy]
# clippy allowed by default
dbg_macro = "warn"

# clippy categories https://doc.rust-lang.org/clippy/
all = "warn"
correctness = "warn"
suspicious = "warn"
style = "warn"
complexity = "warn"
perf = "warn"
pedantic = "warn"
