name: stride
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  rust_lib_stride:
    path: rust_builder
  flutter_rust_bridge: 2.0.0-dev.26
  uuid: ^4.3.3
  path: ^1.9.0
  path_provider: ^2.1.2
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  catppuccin_flutter: ^1.0.0
  table_calendar: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3
  test: ^1.24.9

flutter:
  uses-material-design: true

flutter_rust_bridge:
  rust_input: rust/src/api/**/*.rs
  dart_output: lib/src/rust
