name: stride
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  rust_lib_stride:
    path: rust_builder
  flutter_rust_bridge: "2.0.0"
  uuid: ^4.3.3
  path: ^1.9.0
  path_provider: ^2.1.2
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  freezed_annotation: ^2.4.1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3
  test: ^1.24.9
  freezed: ^2.4.7
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

flutter_rust_bridge:
  rust_input: rust/src/api/**/*.rs
  dart_output: lib/src/rust
