name: stride
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  stride_flutter_bridge:
    path: rust_builder
  flutter_rust_bridge: 2.1.0
  uuid: ^4.4.2
  path: ^1.9.0
  path_provider: ^2.1.3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  test: ^1.25.2
  freezed: ^2.5.2
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
