[package]
name = "rust_lib_stride"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.25"

[build-dependencies]
flutter_rust_bridge_codegen = { version = "2.0.0-dev.25" }
anyhow = { version = "1.0.64", features = ["backtrace"] }
