[package]
name = "stride_flutter_bridge"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = { version = "=2.1.0", features = ["chrono", "uuid"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
uuid = { version = "1.7", features = ["v7", "serde"] }
chrono = { version = "0.4", features = ["serde"]}
derive_builder = "0.20"
anyhow = "1.0"
thiserror = "1.0"
lazy_static = "1.4"
git2 = { version = "0.19", default-features = false, features = ["ssh", "ssh_key_from_memory", "vendored-libgit2", "vendored-openssl"] }
base64 = "0.22"
openssl = { version = "0.10", features = ["vendored"] }
pem = "3.0"
log = "0.4"
env_logger = "0.11"

