name: Publish Release
on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 10406996 # 11.0

      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.80.0

      - name: Verify rust installation
        run: rustc --version

      # Maybe use flutter-version-file, see: https://github.com/subosito/flutter-action
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0

      - name: Verify flutter installation
        run: flutter --version

      - name: Build
        run: |
          # Remove non-reproducable part of path strings.
          export RUSTFLAGS="--remap-path-prefix=$(pwd)=/usr/src"
          cd flutter
          flutter build apk --release --split-per-abi

      - name: Upload Arifact armeabi-v7a
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "flutter/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk"
          asset_name: "stride-armeabi-v7a.apk"
          override: true
          tag: ${{ github.ref }}

      - name: Upload Arifact arm64-v8a
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "flutter/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk"
          asset_name: "stride-arm64-v8a.apk"
          override: true
          tag: ${{ github.ref }}

      - name: Upload Arifact x86_64
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "flutter/build/app/outputs/flutter-apk/app-x86_64-release.apk"
          asset_name: "stride-x86_64.apk"
          override: true
          tag: ${{ github.ref }}
